// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProductSearch.Core.Data;

#nullable disable

namespace ProductSearch.Core.Data.Migrations;

[DbContext(typeof(ProductDbContext))]
[Migration("20260831220000_SplitEmbeddingsByDimension")]
partial class SplitEmbeddingsByDimension
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ProductSearch.Core.Data.ProductEmbedding1152Entity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<object>("ImageEmbedding")
                    .HasColumnType("vector(1152)");

                b.Property<object>("TextEmbedding")
                    .HasColumnType("vector(1152)");

                b.Property<DateTimeOffset>("UpdatedUtc")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("now()");

                b.HasKey("Id");

                b.ToTable("product_embeddings_1152");
            });

        modelBuilder.Entity("ProductSearch.Core.Data.ProductEmbedding768Entity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<object>("ImageEmbedding")
                    .HasColumnType("vector(768)");

                b.Property<object>("TextEmbedding")
                    .HasColumnType("vector(768)");

                b.Property<DateTimeOffset>("UpdatedUtc")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("now()");

                b.HasKey("Id");

                b.ToTable("product_embeddings_768");
            });

        modelBuilder.Entity("ProductSearch.Core.Data.ProductEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ArticleType")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("BaseColour")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("CatalogId")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("ConcatenatedText")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("ImageRelPath")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("MasterCategory")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("ProductDisplayName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("Season")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("SubCategory")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTimeOffset>("UpdatedUtc")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("now()");

                b.Property<string>("Usage")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<int>("Year")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("CatalogId")
                    .IsUnique();

                b.ToTable("products");
            });

        modelBuilder.Entity("ProductSearch.Core.Data.ProductEmbedding1152Entity", b =>
            {
                b.HasOne("ProductSearch.Core.Data.ProductEntity", null)
                    .WithMany()
                    .HasForeignKey("Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("ProductSearch.Core.Data.ProductEmbedding768Entity", b =>
            {
                b.HasOne("ProductSearch.Core.Data.ProductEntity", null)
                    .WithMany()
                    .HasForeignKey("Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
