using FluentAssertions;
using NSubstitute;
using PDDM.Core.Abstractions;
using PDDM.Core.Configuration;
using PDDM.Core.Constants;
using PDDM.Core.Helpers;
using PDDM.Core.Models;
using PDDM.Core.Models.JiraApi;
using PDDM.Core.Services;
using PDDM.Shared;
using PDDM.Shared.Constants;
using PDDM.Shared.Dtos;
using PDDM.Shared.Sse;

namespace PDDM.Core.Tests;

public class DecisionDetectorTests
{
    private readonly DecisionDetector _sut = new();

    [Fact]
    public void IsDecisionComment_WhenKeywordPresent_ReturnsTrue()
        => _sut.IsDecisionComment("We decided to use Netty").Should().BeTrue();

    [Fact]
    public void IsDecisionComment_WhenEmpty_ReturnsFalse()
        => _sut.IsDecisionComment("").Should().BeFalse();

    [Fact]
    public void IsAutoGeneratedComment_WhenPrBot_ReturnsTrue()
        => _sut.IsAutoGeneratedComment("user has created a pull request for this issue").Should().BeTrue();

    [Fact]
    public void IsAutoGeneratedComment_WhenHuman_ReturnsFalse()
        => _sut.IsAutoGeneratedComment("Looks good to me").Should().BeFalse();
}

public class IntentClassifierTests
{
    private readonly IntentClassifier _sut = new();

    [Fact]
    public void Classify_AssignedIssue_WhenKeyInFirstHalf()
        => _sut.Classify("I got assigned SPARK-57337").Should().Be(QueryIntent.AssignedIssue);

    [Fact]
    public void Classify_DecisionRationale()
        => _sut.Classify("Why did they decide to use ANSI mode?").Should().Be(QueryIntent.DecisionRationale);

    [Fact]
    public void Classify_NewRequirement()
        => _sut.Classify("I need to add validation for casting").Should().Be(QueryIntent.NewRequirement);

    [Fact]
    public void Classify_NewRequirement_StringToNumberParaphrase()
        => _sut.Classify("Please handle string-to-number casts that return null").Should().Be(QueryIntent.NewRequirement);

    [Fact]
    public void Classify_Decision_EnableByDefaultParaphrase()
        => _sut.Classify("What is the rationale for enable by default?").Should().Be(QueryIntent.DecisionRationale);

    [Fact]
    public void Classify_GeneralQuestion()
        => _sut.Classify("Tell me about streaming shuffle").Should().Be(QueryIntent.GeneralQuestion);

    [Fact]
    public async Task ClassifyAsync_MatchesHeuristic()
        => (await _sut.ClassifyAsync("I need to add validation")).Should().Be(QueryIntent.NewRequirement);

    [Fact]
    public void ExtractIssueKey_ReturnsUppercase()
        => _sut.ExtractIssueKey("help with spark-123").Should().Be("SPARK-123");

    [Fact]
    public void ExtractIssueKey_WhenMissing_ReturnsNull()
        => _sut.ExtractIssueKey("no key here").Should().BeNull();
}

public class HybridIntentClassifierTests
{
    [Fact]
    public async Task ClassifyAsync_UsesHeuristic_WhenHighConfidence()
    {
        var chat = Substitute.For<IChatService>();
        var sut = new HybridIntentClassifier(new IntentClassifier(), chat);
        (await sut.ClassifyAsync("I need to add validation")).Should().Be(QueryIntent.NewRequirement);
        await chat.DidNotReceiveWithAnyArgs().CompleteAsync(default!, default!, default);
    }

    [Fact]
    public async Task ClassifyAsync_UsesLlm_WhenAmbiguousParaphrase()
    {
        var chat = Substitute.For<IChatService>();
        chat.CompleteAsync(
                Arg.Any<string>(),
                Arg.Any<string>(),
                Arg.Any<CancellationToken>(),
                Arg.Any<float?>(),
                Arg.Any<int?>())
            .Returns("""{"intent":"DecisionRationale","issueKey":null}""");

        var sut = new HybridIntentClassifier(new IntentClassifier(), chat);
        (await sut.ClassifyAsync("Walk me through the historical tradeoffs for SQL mode defaults"))
            .Should().Be(QueryIntent.DecisionRationale);
        await chat.Received(1).CompleteAsync(
            Arg.Any<string>(),
            Arg.Any<string>(),
            Arg.Any<CancellationToken>(),
            Arg.Any<float?>(),
            Arg.Any<int?>());
    }

    [Fact]
    public async Task ClassifyAsync_HeuristicCatchesAnsiDecisionParaphrase()
    {
        var chat = Substitute.For<IChatService>();
        var sut = new HybridIntentClassifier(new IntentClassifier(), chat);
        (await sut.ClassifyAsync("Explain the ANSI mode choice in Spark 4")).Should().Be(QueryIntent.DecisionRationale);
        await chat.DidNotReceiveWithAnyArgs().CompleteAsync(default!, default!, default);
    }

    [Fact]
    public async Task ClassifyAsync_FallsBackToGeneral_WhenLlmFails()
    {
        var chat = Substitute.For<IChatService>();
        chat.CompleteAsync(
                Arg.Any<string>(),
                Arg.Any<string>(),
                Arg.Any<CancellationToken>(),
                Arg.Any<float?>(),
                Arg.Any<int?>())
            .Returns<Task<string>>(_ => throw new HttpRequestException("down"));

        var sut = new HybridIntentClassifier(new IntentClassifier(), chat);
        (await sut.ClassifyAsync("Tell me about shuffle")).Should().Be(QueryIntent.GeneralQuestion);
    }

    [Theory]
    [InlineData("""{"intent":"NewRequirement"}""", QueryIntent.NewRequirement)]
    [InlineData("```json\n{\"intent\":\"AssignedIssue\",\"issueKey\":\"SPARK-1\"}\n```", QueryIntent.AssignedIssue)]
    [InlineData("noise {\"intent\":\"DecisionRationale\"} trailing", QueryIntent.DecisionRationale)]
    [InlineData("<think>reasoning</think>{\"intent\":\"NewRequirement\"}", QueryIntent.NewRequirement)]
    public void ParseIntent_AcceptsJsonVariants(string raw, QueryIntent expected)
        => HybridIntentClassifier.ParseIntent(raw).Should().Be(expected);
}

public class PromptBuilderTests
{
    [Fact]
    public void BuildUserPrompt_IncludesScenario()
    {
        var prompt = PddmDefaults.BuildUserPrompt("ctx", "q?", QueryIntent.DecisionRationale);
        prompt.Should().Contain("SCENARIO: DecisionRationale").And.Contain("ctx").And.Contain("q?");
        prompt.Should().Contain("Follow the system Structure").And.Contain("Sources last");
    }

    [Fact]
    public void BuildSystemPrompt_IncludesOnlyMatchingStructure()
    {
        var prompt = PddmDefaults.BuildSystemPrompt(QueryIntent.AssignedIssue);
        prompt.Should().Contain("Assigned ticket").And.NotContain("New requirement");
        prompt.Should().Contain("### Your issue").And.Contain("Sources");
    }

    [Fact]
    public void BuildSystemPrompt_Decision_IncludesRationaleSkeleton()
    {
        var prompt = PddmDefaults.BuildSystemPrompt(QueryIntent.DecisionRationale);
        prompt.Should().Contain("### Rationale")
            .And.Contain("Never invent SPARK keys not present in CONTEXT");
    }

    [Fact]
    public void IntentClassifySystemPrompt_IncludesExamples()
    {
        PddmDefaults.IntentClassifySystemPrompt.Should().Contain("SPARK-57337")
            .And.Contain("NewRequirement")
            .And.Contain("DecisionRationale");
    }
}

public class ChunkIdFormatterTests
{
    [Fact]
    public void FormatIssueId_Epic()
        => ChunkIdFormatter.FormatIssueId(JiraIssueTypeNames.Epic, "SPARK-1").Should().Be("epic_SPARK-1");

    [Fact]
    public void FormatCommentId()
        => ChunkIdFormatter.FormatCommentId("SPARK-1", 2).Should().Be("comment_SPARK-1_2");

    [Fact]
    public void PossibleIdsForKey_ContainsPrefixes()
        => ChunkIdFormatter.PossibleIdsForKey("SPARK-1").Should().Contain("story_SPARK-1");
}

public class TierMapperTests
{
    [Theory]
    [InlineData(JiraIssueTypeNames.Epic, 0)]
    [InlineData(JiraIssueTypeNames.Bug, 1)]
    [InlineData(JiraIssueTypeNames.SubTask, 2)]
    public void DetermineTier(string type, int expected)
        => TierMapper.DetermineTier(type).Should().Be(expected);
}

public class TextTruncatorTests
{
    [Fact]
    public void Truncate_Short_Unchanged()
        => TextTruncator.Truncate("abc", 10).Should().Be("abc");

    [Fact]
    public void Truncate_Long_AppendsEllipsis()
        => TextTruncator.Truncate("abcdefghij", 5).Should().Be("abcde...");
}

public class ChunkingServiceTests
{
    [Fact]
    public void CreateChunks_SetsParentKeyForSubtask()
    {
        var runtime = new PddmRuntimeSettings(new PddmSettings());
        var sut = new ChunkingService(new DecisionDetector(), runtime);
        var issues = new List<JiraIssue>
        {
            new()
            {
                Key = "SPARK-2",
                Fields = new JiraIssueFields
                {
                    Issuetype = new JiraIssueType { Name = JiraIssueTypeNames.SubTask, Subtask = true },
                    Summary = "Sub",
                    Parent = new JiraParentIssue { Key = "SPARK-1" },
                    Comment = new JiraComments { Comments = [] }
                }
            }
        };

        var chunks = sut.CreateChunks(issues);
        chunks.Should().ContainSingle();
        chunks[0].ParentKey.Should().Be("SPARK-1");
        chunks[0].Id.Should().Be("subtask_SPARK-2");
    }

    [Fact]
    public void CreateChunks_SkipsLowCommentBugs()
    {
        var settings = new PddmSettings();
        settings.Ingestion.MinCommentsForIssue = 2;
        var runtime = new PddmRuntimeSettings(settings);
        var sut = new ChunkingService(new DecisionDetector(), runtime);
        var issues = new List<JiraIssue>
        {
            new()
            {
                Key = "SPARK-9",
                Fields = new JiraIssueFields
                {
                    Issuetype = new JiraIssueType { Name = JiraIssueTypeNames.Bug },
                    Summary = "Bug",
                    Comment = new JiraComments { Comments = [new JiraComment { Body = "only one" }] }
                }
            }
        };

        sut.CreateChunks(issues).Should().BeEmpty();
    }

    [Fact]
    public void ComposeEmbeddingText_CommentUsesAuthorFormat()
    {
        var sut = new ChunkingService(new DecisionDetector(), new PddmRuntimeSettings(new PddmSettings()));
        var text = sut.ComposeEmbeddingText(new JiraDocChunk
        {
            Tier = (int)DocTier.Comment,
            ParentKey = "SPARK-1",
            CommentAuthor = "Alice",
            Description = "We decided X"
        });
        text.Should().Be("On SPARK-1: Alice said: We decided X");
    }
}

public class HybridIndexServiceTests
{
    [Fact]
    public void Add_CommentDoesNotOverwriteIssueKey()
    {
        var store = Substitute.For<IVectorStore>();
        var sut = new HybridIndexService(store);
        sut.Add(new JiraDocChunk { Id = "bug_SPARK-1", Key = "SPARK-1", Tier = (int)DocTier.Issue, Summary = "Bug" });
        sut.Add(new JiraDocChunk { Id = "comment_SPARK-1_0", Key = "SPARK-1", Tier = (int)DocTier.Comment, ParentKey = "SPARK-1" });

        sut.GetByKey("SPARK-1")!.Summary.Should().Be("Bug");
        sut.GetById("comment_SPARK-1_0").Should().NotBeNull();
        sut.GetByParentKey("SPARK-1").Should().HaveCount(1);
    }

    [Fact]
    public async Task RebuildFromStoreAsync_FetchesIds()
    {
        var store = Substitute.For<IVectorStore>();
        store.LoadChunkIdsAsync(Arg.Any<CancellationToken>()).Returns(["epic_SPARK-1"]);
        store.FetchById("epic_SPARK-1", false).Returns(new JiraDocChunk
        {
            Id = "epic_SPARK-1",
            Key = "SPARK-1",
            Tier = (int)DocTier.EpicOrUmbrella,
            Summary = "Epic"
        });

        var sut = new HybridIndexService(store);
        await sut.RebuildFromStoreAsync();
        sut.GetByKey("SPARK-1")!.Summary.Should().Be("Epic");
        sut.TotalCount.Should().Be(1);
    }

    [Fact]
    public void Clear_EmptiesIndex()
    {
        var sut = new HybridIndexService(Substitute.For<IVectorStore>());
        sut.Add(new JiraDocChunk { Id = "epic_1", Key = "SPARK-1", Tier = 0 });
        sut.Clear();
        sut.TotalCount.Should().Be(0);
        sut.GetByTier(0).Should().BeEmpty();
    }
}

public class ContextBuilderServiceTests
{
    [Fact]
    public void Build_AssignedIssue_IncludesEpicAndCentral()
    {
        var sut = new ContextBuilderService();
        var ctx = new NavigatedContext
        {
            ParentEpic = new JiraDocChunk { Key = "SPARK-10", Summary = "Epic", Description = "D", Status = "Open" },
            CentralIssue = new JiraDocChunk { Key = "SPARK-11", IssueType = "Story", Summary = "Story", Status = "Open", Priority = "Major" }
        };

        var text = sut.Build(ctx, QueryIntent.AssignedIssue);
        text.Should().Contain("SPARK-10").And.Contain("SPARK-11");
    }

    [Fact]
    public void Build_AssignedIssue_OrdersEpicCentralThenSiblings()
    {
        var sut = new ContextBuilderService();
        var ctx = new NavigatedContext
        {
            ParentEpic = new JiraDocChunk { Key = "SPARK-10", Summary = "Epic", Description = "D", Status = "Open" },
            CentralIssue = new JiraDocChunk { Key = "SPARK-11", IssueType = "Story", Summary = "Story", Status = "Open", Priority = "Major" },
            SiblingIssues =
            [
                new JiraDocChunk { Key = "SPARK-12", Summary = "Sibling", Status = "Open", Tier = (int)DocTier.Issue }
            ],
            SubTasks =
            [
                new JiraDocChunk { Key = "SPARK-13", Summary = "Sub", Status = "Open", Tier = (int)DocTier.SubTask }
            ]
        };

        var text = sut.Build(ctx, QueryIntent.AssignedIssue);
        var epicAt = text.IndexOf("EPIC: SPARK-10", StringComparison.Ordinal);
        var centralAt = text.IndexOf("Central issue: SPARK-11", StringComparison.Ordinal);
        var siblingAt = text.IndexOf("Sibling work:", StringComparison.Ordinal);
        var subAt = text.IndexOf("Sub-tasks:", StringComparison.Ordinal);
        epicAt.Should().BeGreaterThanOrEqualTo(0);
        centralAt.Should().BeGreaterThan(epicAt);
        siblingAt.Should().BeGreaterThan(centralAt);
        subAt.Should().BeGreaterThan(siblingAt);
        text.Should().Contain("SPARK-13");
    }

    [Fact]
    public void Build_AssignedIssue_IncludesJiraBrowseUrls()
    {
        var sut = new ContextBuilderService();
        var ctx = new NavigatedContext
        {
            ParentEpic = new JiraDocChunk { Key = "SPARK-10", Summary = "Epic", Description = "D", Status = "Open" },
            CentralIssue = new JiraDocChunk { Key = "SPARK-11", IssueType = "Story", Summary = "Story", Status = "Open", Priority = "Major" }
        };

        var text = sut.Build(ctx, QueryIntent.AssignedIssue);
        var epicUrl = string.Format(SharedPddmDefaults.JiraBrowseUrlFormat, "SPARK-10");
        var issueUrl = string.Format(SharedPddmDefaults.JiraBrowseUrlFormat, "SPARK-11");
        text.Should().Contain($"Url: {epicUrl}").And.Contain($"Url: {issueUrl}");
    }

    [Fact]
    public void Build_CommentList_UsesParentKeyBrowseUrl()
    {
        var sut = new ContextBuilderService();
        var ctx = new NavigatedContext
        {
            DecisionComments =
            [
                new JiraDocChunk
                {
                    Key = "SPARK-11",
                    ParentKey = "SPARK-11",
                    Tier = (int)DocTier.Comment,
                    Description = "We decided X",
                    Status = "Open"
                }
            ]
        };

        var text = sut.Build(ctx, QueryIntent.DecisionRationale);
        text.Should().Contain($"Url: {string.Format(SharedPddmDefaults.JiraBrowseUrlFormat, "SPARK-11")}");
    }

    [Fact]
    public void Build_NewRequirement_Empty_UsesIngestMessage()
    {
        var sut = new ContextBuilderService();
        var text = sut.Build(new NavigatedContext(), QueryIntent.NewRequirement);
        text.Should().Contain("No related tickets in the index yet");
        text.Should().NotContain("No exact match found for this requirement.");
        text.Should().NotContain("No exact ticket for this ask");
    }

    [Fact]
    public void Build_NewRequirement_WithLandscape_UsesSoftPrefix()
    {
        var sut = new ContextBuilderService();
        var ctx = new NavigatedContext
        {
            StandaloneRelatedIssues =
            [
                new JiraDocChunk { Key = "SPARK-44444", Summary = "ANSI default", Status = "Resolved", Tier = (int)DocTier.Issue }
            ]
        };

        var text = sut.Build(ctx, QueryIntent.NewRequirement);
        text.Should().Contain("No exact ticket for this ask; related landscape:");
        text.Should().Contain("SPARK-44444");
        text.Should().NotContain("No exact match found for this requirement.");
    }

    [Fact]
    public void Build_GeneralQuestion_DoesNotSayRequirement()
    {
        var sut = new ContextBuilderService();
        var text = sut.Build(new NavigatedContext(), QueryIntent.GeneralQuestion);
        text.Should().Contain("Relevant landscape").And.NotContain("No exact match found for this requirement.");
    }

    [Fact]
    public void Build_NotFound_ReturnsAssembled()
    {
        var sut = new ContextBuilderService();
        var ctx = NavigatedContext.NotFound("SPARK-404");
        var text = sut.Build(ctx, QueryIntent.AssignedIssue);
        text.Should().Contain("SPARK-404");
        text.Should().Contain(string.Format(SharedPddmDefaults.JiraBrowseUrlFormat, "SPARK-404"));
    }

    [Fact]
    public void Build_TruncatesLongDescriptions_KeepsKeyAndSummary()
    {
        var sut = new ContextBuilderService();
        var longDesc = new string('x', PddmDefaults.ContextMaxDescriptionChars + 200);
        var ctx = new NavigatedContext
        {
            CentralIssue = new JiraDocChunk
            {
                Key = "SPARK-11",
                IssueType = "Story",
                Summary = "Keep me",
                Description = longDesc,
                Status = "Open",
                Priority = "Major"
            }
        };

        var text = sut.Build(ctx, QueryIntent.AssignedIssue);
        text.Should().Contain("SPARK-11").And.Contain("Keep me").And.Contain("...");
        text.Length.Should().BeLessThan(longDesc.Length);
    }
}

public class OfflineGoldenPromptHarnessTests
{
    [Theory]
    [InlineData(QueryIntent.AssignedIssue, "### Your issue")]
    [InlineData(QueryIntent.NewRequirement, "### Related landscape")]
    [InlineData(QueryIntent.DecisionRationale, "### Rationale")]
    [InlineData(QueryIntent.GeneralQuestion, "### Related landscape")]
    public void SystemPrompt_ContainsScenarioSkeleton(QueryIntent intent, string expectedSection)
    {
        var system = PddmDefaults.BuildSystemPrompt(intent);
        system.Should().Contain(expectedSection).And.Contain("Sources");
        system.Should().Contain("Suggest running Ingestion ONLY when CONTEXT is empty");
    }

    [Fact]
    public void UserPrompt_ForDemoAssigned_IncludesContextAndScenario()
    {
        var ctx = new ContextBuilderService().Build(
            new NavigatedContext
            {
                ParentEpic = new JiraDocChunk { Key = "SPARK-1", Summary = "Epic", Description = "biz", Status = "Open" },
                CentralIssue = new JiraDocChunk
                {
                    Key = GoldenDemoSeedKeys.AssignedTicket,
                    IssueType = "Bug",
                    Summary = "Assigned",
                    Description = "desc",
                    Status = "Open",
                    Priority = "Major"
                }
            },
            QueryIntent.AssignedIssue);

        var user = PddmDefaults.BuildUserPrompt(ctx, GoldenDemoQuestions.AssignedTicket, QueryIntent.AssignedIssue);
        user.Should().Contain("SCENARIO: AssignedIssue")
            .And.Contain(GoldenDemoSeedKeys.AssignedTicket)
            .And.Contain(GoldenDemoQuestions.AssignedTicket)
            .And.Contain("markdown links only from CONTEXT Url lines");
    }
}

public class NavigatedContextTests
{
    [Fact]
    public void NotFound_IncludesApacheBrowseUrl()
    {
        var ctx = NavigatedContext.NotFound("SPARK-57337");
        ctx.AssembledContext.Should().Contain("https://issues.apache.org/jira/browse/SPARK-57337");
        ctx.AssembledContext.Should().NotContain("jira.example.com");
    }
}

public class JiraFetcherUrlTests
{
    [Fact]
    public void BuildSearchUrl_UsesFieldsNotExpandComments()
    {
        var url = JiraFetcherService.BuildSearchUrl("project=SPARK", 0, 50);
        url.Should().Contain("fields=");
        url.Should().Contain(Uri.EscapeDataString("comment"));
        url.Should().Contain(Uri.EscapeDataString("customfield_12311120"));
        url.Should().NotContain("expand=comments");
    }
}

public class NavigationEngineTests
{
    [Fact]
    public async Task NavigateFromAssignedIssueAsync_NotFound()
    {
        var store = Substitute.For<IVectorStore>();
        var hybrid = Substitute.For<IHybridIndex>();
        var embed = Substitute.For<IEmbeddingService>();
        var intent = Substitute.For<IIntentClassifier>();
        var context = Substitute.For<IContextBuilder>();
        hybrid.GetByKey("SPARK-404").Returns((JiraDocChunk?)null);
        store.FetchByKey("SPARK-404", false).Returns((JiraDocChunk?)null);

        var sut = new NavigationEngine(store, hybrid, embed, intent, context);
        var result = await sut.NavigateFromAssignedIssueAsync("SPARK-404");
        result.AssembledContext.Should().Contain("SPARK-404");
        result.AssembledContext.Should().Contain("https://issues.apache.org/jira/browse/SPARK-404");
    }

    [Fact]
    public async Task NavigateFromAssignedIssueAsync_LoadsHierarchyAndCross()
    {
        var store = Substitute.For<IVectorStore>();
        var hybrid = Substitute.For<IHybridIndex>();
        var embed = Substitute.For<IEmbeddingService>();
        var intent = Substitute.For<IIntentClassifier>();
        var context = Substitute.For<IContextBuilder>();

        var issue = new JiraDocChunk
        {
            Id = "story_SPARK-2",
            Key = "SPARK-2",
            Tier = (int)DocTier.Issue,
            EpicLink = "SPARK-1",
            Summary = "Story",
            Description = "Desc"
        };
        hybrid.GetByKey("SPARK-2").Returns(issue);
        hybrid.GetByKey("SPARK-1").Returns(new JiraDocChunk { Key = "SPARK-1", Tier = 0, Summary = "Epic" });
        hybrid.GetByEpicLink("SPARK-1").Returns([issue, new JiraDocChunk { Key = "SPARK-3", Tier = 1, Summary = "Sibling" }]);
        hybrid.GetByParentKey("SPARK-2").Returns([]);
        embed.EmbedSingleAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(new ReadOnlyMemory<float>(new float[PddmDefaults.EmbeddingDimensions]));
        store.Query(Arg.Any<ReadOnlyMemory<float>>(), Arg.Any<int>(), Arg.Any<Func<JiraDocChunk, bool>?>(), false, null, (int)DocTier.Issue, "SPARK-2")
            .Returns([]);

        var sut = new NavigationEngine(store, hybrid, embed, intent, context);
        var result = await sut.NavigateFromAssignedIssueAsync("SPARK-2");
        result.ParentEpic!.Key.Should().Be("SPARK-1");
        result.SiblingIssues.Should().ContainSingle(s => s.Key == "SPARK-3");
    }

    [Fact]
    public async Task NavigateFromNewRequirementAsync_ClustersByEpic()
    {
        var store = Substitute.For<IVectorStore>();
        var hybrid = Substitute.For<IHybridIndex>();
        var embed = Substitute.For<IEmbeddingService>();
        var intent = Substitute.For<IIntentClassifier>();
        var context = Substitute.For<IContextBuilder>();
        embed.EmbedSingleAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(new ReadOnlyMemory<float>(new float[768]));
        store.Query(Arg.Any<ReadOnlyMemory<float>>(), Arg.Any<int>(), Arg.Any<Func<JiraDocChunk, bool>?>(), false, null, null, null)
            .Returns([
                new ZVecHitAdapter
                {
                    Record = new JiraDocChunk { Key = "SPARK-2", EpicLink = "SPARK-1", Tier = 1 },
                    Score = 0.9f
                }
            ]);
        hybrid.GetByKey("SPARK-1").Returns(new JiraDocChunk { Key = "SPARK-1", Tier = 0, Summary = "Epic" });
        hybrid.GetByEpicLink("SPARK-1").Returns([new JiraDocChunk { Key = "SPARK-2", Tier = 1 }]);

        var sut = new NavigationEngine(store, hybrid, embed, intent, context);
        var result = await sut.NavigateFromNewRequirementAsync("need validation");
        result.RelatedEpics.Should().ContainSingle(e => e.Key == "SPARK-1");
    }

    [Fact]
    public async Task NavigateFromDecisionQuestionAsync_FallsBackToIssueTier()
    {
        var store = Substitute.For<IVectorStore>();
        var hybrid = Substitute.For<IHybridIndex>();
        var embed = Substitute.For<IEmbeddingService>();
        var intent = Substitute.For<IIntentClassifier>();
        var context = Substitute.For<IContextBuilder>();
        embed.EmbedSingleAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(new ReadOnlyMemory<float>(new float[768]));
        store.Query(Arg.Any<ReadOnlyMemory<float>>(), Arg.Any<int>(), Arg.Any<Func<JiraDocChunk, bool>?>(), false, true, (int)DocTier.Comment, null)
            .Returns([]);
        store.Query(Arg.Any<ReadOnlyMemory<float>>(), Arg.Any<int>(), Arg.Any<Func<JiraDocChunk, bool>?>(), false, null, (int)DocTier.Comment, null)
            .Returns([]);
        store.Query(Arg.Any<ReadOnlyMemory<float>>(), Arg.Any<int>(), Arg.Any<Func<JiraDocChunk, bool>?>(), false, null, (int)DocTier.Issue, null)
            .Returns([
                new ZVecHitAdapter
                {
                    Record = new JiraDocChunk
                    {
                        Key = "SPARK-44444",
                        Tier = (int)DocTier.Issue,
                        Summary = "Use ANSI SQL mode by default",
                        Description = "Enable ansi by default"
                    },
                    Score = 0.9f
                }
            ]);

        var sut = new NavigationEngine(store, hybrid, embed, intent, context);
        var result = await sut.NavigateFromDecisionQuestionAsync("Why ANSI default?");
        result.ParentIssues.Should().ContainSingle(i => i.Key == "SPARK-44444");
    }

    [Fact]
    public async Task NavigateFromDecisionQuestionAsync_WalksUp()
    {
        var store = Substitute.For<IVectorStore>();
        var hybrid = Substitute.For<IHybridIndex>();
        var embed = Substitute.For<IEmbeddingService>();
        var intent = Substitute.For<IIntentClassifier>();
        var context = Substitute.For<IContextBuilder>();
        embed.EmbedSingleAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(new ReadOnlyMemory<float>(new float[768]));
        store.Query(Arg.Any<ReadOnlyMemory<float>>(), Arg.Any<int>(), Arg.Any<Func<JiraDocChunk, bool>?>(), false, true, (int)DocTier.Comment, null)
            .Returns([
                new ZVecHitAdapter
                {
                    Record = new JiraDocChunk
                    {
                        Key = "SPARK-2",
                        ParentKey = "SPARK-2",
                        EpicLink = "SPARK-1",
                        Tier = 3,
                        ContainsDecision = true,
                        Description = "decided"
                    },
                    Score = 1f
                }
            ]);
        hybrid.GetByKey("SPARK-2").Returns(new JiraDocChunk { Key = "SPARK-2", Tier = 1 });
        hybrid.GetByKey("SPARK-1").Returns(new JiraDocChunk { Key = "SPARK-1", Tier = 0 });

        var sut = new NavigationEngine(store, hybrid, embed, intent, context);
        var result = await sut.NavigateFromDecisionQuestionAsync("why did they decide");
        result.DecisionComments.Should().NotBeEmpty();
        result.ParentEpics.Should().ContainSingle();
    }

    [Fact]
    public async Task NavigateAsync_GeneralRoutesToRequirementPath()
    {
        var store = Substitute.For<IVectorStore>();
        var hybrid = Substitute.For<IHybridIndex>();
        var embed = Substitute.For<IEmbeddingService>();
        var intent = new IntentClassifier();
        var context = new ContextBuilderService();
        embed.EmbedSingleAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(new ReadOnlyMemory<float>(new float[PddmDefaults.EmbeddingDimensions]));
        store.Query(Arg.Any<ReadOnlyMemory<float>>(), Arg.Any<int>(), Arg.Any<Func<JiraDocChunk, bool>?>(), false, null, null, null)
            .Returns([]);

        var sut = new NavigationEngine(store, hybrid, embed, intent, context);
        var result = await sut.NavigateAsync("Tell me about shuffle", QueryIntent.GeneralQuestion);
        result.Intent.Should().Be(QueryIntent.GeneralQuestion);
        result.AssembledContext.Should().Contain("landscape");
        result.AssembledContext.Should().NotContain("No exact match found for this requirement.");
    }
}

public class SettingsServiceTests
{
    [Fact]
    public void UpdateLmStudioSettings_RejectsDimensionChange()
    {
        var runtime = new PddmRuntimeSettings(new PddmSettings());
        var embed = Substitute.For<IEmbeddingService>();
        var sut = new SettingsService(runtime, embed);
        var act = () => sut.UpdateLmStudioSettings(new LmStudioSettingsDto { EmbeddingDimensions = 384 });
        act.Should().Throw<InvalidOperationException>();
    }

    [Fact]
    public void GetAndUpdate_RoundTrip()
    {
        var runtime = new PddmRuntimeSettings(new PddmSettings());
        var embed = Substitute.For<IEmbeddingService>();
        var sut = new SettingsService(runtime, embed);
        sut.UpdateLmStudioSettings(new LmStudioSettingsDto
        {
            BaseUrl = "http://localhost:9999/v1",
            EmbeddingModel = "m",
            ChatModel = "c",
            EmbeddingDimensions = PddmDefaults.EmbeddingDimensions
        });
        sut.GetLmStudioSettings().BaseUrl.Should().Be("http://localhost:9999/v1");
    }

    [Fact]
    public async Task VerifyLmStudioAsync_Delegates()
    {
        var runtime = new PddmRuntimeSettings(new PddmSettings());
        var embed = Substitute.For<IEmbeddingService>();
        embed.VerifyLmStudioAsync(Arg.Any<CancellationToken>()).Returns(true);
        var sut = new SettingsService(runtime, embed);
        (await sut.VerifyLmStudioAsync()).Should().BeTrue();
    }
}

public class SseEventParserTests
{
    private readonly SseEventParser _sut = new();

    [Fact]
    public void Parse_Intent()
    {
        var result = _sut.Parse(SseEventTypes.Intent, """{"Intent":1,"IssueKey":"SPARK-1"}""") as IntentEventDto;
        result!.Intent.Should().Be(QueryIntent.NewRequirement);
        result.IssueKey.Should().Be("SPARK-1");
    }

    [Fact]
    public void Parse_Token()
        => (_sut.Parse(SseEventTypes.Token, """{"Token":"hi"}""") as TokenEventDto)!.Token.Should().Be("hi");

    [Fact]
    public void Parse_Progress()
    {
        var result = _sut.Parse(
            SseEventTypes.Progress,
            """{"Phase":"classifying","Message":"Classifying intent…"}""") as ProgressEventDto;
        result!.Phase.Should().Be(ChatProgressPhases.Classifying);
        result.Message.Should().Be("Classifying intent…");
    }

    [Fact]
    public void Parse_Unknown_ReturnsNull()
        => _sut.Parse("nope", "{}").Should().BeNull();
}

public class IngestionOrchestratorTests
{
    [Fact]
    public void GetProgress_StartsNotStarted()
    {
        var sut = CreateSut(out _, out _, out _, out _, out _);
        sut.GetProgress().Status.Should().Be(IngestionStatus.NotStarted);
    }

    [Fact]
    public async Task RunAsync_HappyPath()
    {
        var sut = CreateSut(out var jira, out var chunking, out var embed, out var store, out var hybrid);
        jira.FetchByTypeAsync(Arg.Any<string>(), Arg.Any<int>(), Arg.Any<CancellationToken>())
            .Returns(callInfo =>
            {
                var type = callInfo.ArgAt<string>(0);
                if (type == JiraIssueTypeNames.Story)
                {
                    return new List<JiraIssue>
                    {
                        new()
                        {
                            Key = "SPARK-1",
                            Fields = new JiraIssueFields
                            {
                                Issuetype = new JiraIssueType { Name = JiraIssueTypeNames.Story },
                                Summary = "S",
                                Comment = new JiraComments { Comments = [] }
                            }
                        }
                    };
                }

                return [];
            });
        jira.FetchByJqlAsync(Arg.Any<string>(), Arg.Any<int>(), Arg.Any<CancellationToken>()).Returns([]);
        jira.FetchSingleAsync(Arg.Any<string>(), Arg.Any<CancellationToken>()).Returns((JiraIssue?)null);
        chunking.CreateChunks(Arg.Any<IReadOnlyList<JiraIssue>>()).Returns([
            new JiraDocChunk { Id = "story_SPARK-1", Key = "SPARK-1", Tier = 1, Summary = "S" }
        ]);
        embed.EmbedBatchAsync(Arg.Any<IReadOnlyList<string>>(), Arg.Any<CancellationToken>())
            .Returns([new ReadOnlyMemory<float>(new float[768])]);
        store.SaveChunkIdsAsync(Arg.Any<IEnumerable<string>>(), Arg.Any<CancellationToken>()).Returns(Task.CompletedTask);

        var progress = await sut.RunAsync();
        progress.Status.Should().Be(IngestionStatus.Completed);
        store.Received(1).RecreateCollection();
        hybrid.Received().Clear();
        await jira.Received().FetchByTypeAsync(JiraIssueTypeNames.SubTask, Arg.Any<int>(), Arg.Any<CancellationToken>());
        await jira.Received().FetchSingleAsync(GoldenDemoSeedKeys.AssignedTicket, Arg.Any<CancellationToken>());
        await jira.Received().FetchSingleAsync(GoldenDemoSeedKeys.AnsiDefaultDecision, Arg.Any<CancellationToken>());
        await jira.Received().FetchByJqlAsync(Arg.Is<string>(j => j.Contains("ANSI")), Arg.Any<int>(), Arg.Any<CancellationToken>());
    }

    private static IngestionOrchestrator CreateSut(
        out IJiraFetcher jira,
        out IChunkingService chunking,
        out IEmbeddingService embed,
        out IVectorStore store,
        out IHybridIndex hybrid)
    {
        jira = Substitute.For<IJiraFetcher>();
        chunking = Substitute.For<IChunkingService>();
        embed = Substitute.For<IEmbeddingService>();
        store = Substitute.For<IVectorStore>();
        hybrid = Substitute.For<IHybridIndex>();
        return new IngestionOrchestrator(jira, chunking, embed, store, hybrid, new PddmRuntimeSettings(new PddmSettings()));
    }
}

public class ChatServiceTests
{
    [Fact]
    public async Task CompleteAsync_AggregatesTokens_WhenStreamEmpty()
    {
        // ChatService requires real HTTP — verify construction only via interface contract with substitute consumer
        var chat = Substitute.For<IChatService>();
        chat.CompleteAsync(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<CancellationToken>(), Arg.Any<float?>(), Arg.Any<int?>())
            .Returns("ok");
        (await chat.CompleteAsync("s", "u")).Should().Be("ok");
    }
}

public class VectorStoreQueryContractTests
{
    [Fact]
    public void IVectorStore_Query_CanBeMocked()
    {
        var store = Substitute.For<IVectorStore>();
        store.FetchByKey("SPARK-1", false).Returns(new JiraDocChunk { Key = "SPARK-1" });
        store.FetchByKey("SPARK-1", false)!.Key.Should().Be("SPARK-1");
        store.FetchById("epic_SPARK-1", false).Returns(new JiraDocChunk { Id = "epic_SPARK-1" });
        store.FetchById("epic_SPARK-1", false)!.Id.Should().Be("epic_SPARK-1");
        store.InsertBatch([]);
        store.Received(1).InsertBatch(Arg.Any<IReadOnlyList<JiraDocChunk>>());
    }
}

public class JiraFetcherContractTests
{
    [Fact]
    public async Task IJiraFetcher_Methods_AreCallableViaSubstitute()
    {
        var fetcher = Substitute.For<IJiraFetcher>();
        fetcher.FetchByTypeAsync(JiraIssueTypeNames.Epic, 1, Arg.Any<CancellationToken>()).Returns([]);
        fetcher.FetchByJqlAsync(Arg.Any<string>(), 1, Arg.Any<CancellationToken>()).Returns([]);
        fetcher.FetchEpicChildrenAsync("SPARK-1", Arg.Any<CancellationToken>()).Returns([]);
        fetcher.FetchSingleAsync("SPARK-1", Arg.Any<CancellationToken>()).Returns((JiraIssue?)null);

        (await fetcher.FetchByTypeAsync(JiraIssueTypeNames.Epic, 1)).Should().BeEmpty();
        (await fetcher.FetchByJqlAsync("project=SPARK", 1)).Should().BeEmpty();
        (await fetcher.FetchEpicChildrenAsync("SPARK-1")).Should().BeEmpty();
        (await fetcher.FetchSingleAsync("SPARK-1")).Should().BeNull();
    }
}

public class EmbeddingServiceContractTests
{
    [Fact]
    public async Task IEmbeddingService_Methods_AreCallableViaSubstitute()
    {
        var embed = Substitute.For<IEmbeddingService>();
        embed.EmbedSingleAsync("t", Arg.Any<CancellationToken>()).Returns(new ReadOnlyMemory<float>(new float[768]));
        embed.EmbedBatchAsync(Arg.Any<IReadOnlyList<string>>(), Arg.Any<CancellationToken>())
            .Returns([new ReadOnlyMemory<float>(new float[768])]);
        embed.VerifyLmStudioAsync(Arg.Any<CancellationToken>()).Returns(true);

        (await embed.EmbedSingleAsync("t")).Length.Should().Be(768);
        (await embed.EmbedBatchAsync(["a"])).Should().HaveCount(1);
        (await embed.VerifyLmStudioAsync()).Should().BeTrue();
    }
}
