using PDDM.Core.Models;
using PDDM.Core.Models.JiraApi;
using PDDM.Shared;
using PDDM.Shared.Dtos;

namespace PDDM.Core.Abstractions;

/// <summary>Flags decision comments and filters auto-generated noise.</summary>
public interface IDecisionDetector
{
    /// <summary>Returns true when comment body matches decision heuristics.</summary>
    bool IsDecisionComment(string commentBody);

    /// <summary>Returns true when comment should be skipped (bots / PR links).</summary>
    bool IsAutoGeneratedComment(string commentBody);
}

/// <summary>Fetches issues from Apache Jira REST API.</summary>
public interface IJiraFetcher
{
    /// <summary>Fetches issues of a given type up to <paramref name="maxTotal"/>.</summary>
    Task<IReadOnlyList<JiraIssue>> FetchByTypeAsync(string issueType, int maxTotal, CancellationToken cancellationToken = default);

    /// <summary>Fetches issues matching arbitrary JQL up to <paramref name="maxTotal"/>.</summary>
    Task<IReadOnlyList<JiraIssue>> FetchByJqlAsync(string jql, int maxTotal, CancellationToken cancellationToken = default);

    /// <summary>Fetches children of an Epic via Epic Link JQL.</summary>
    Task<IReadOnlyList<JiraIssue>> FetchEpicChildrenAsync(string epicKey, CancellationToken cancellationToken = default);

    /// <summary>Fetches a single issue with comments.</summary>
    Task<JiraIssue?> FetchSingleAsync(string issueKey, CancellationToken cancellationToken = default);
}

/// <summary>Creates four-tier <see cref="JiraDocChunk"/> documents from Jira issues.</summary>
public interface IChunkingService
{
    /// <summary>Creates chunks for the given issues (applies comment caps).</summary>
    IReadOnlyList<JiraDocChunk> CreateChunks(IReadOnlyList<JiraIssue> issues);

    /// <summary>Composes the text sent to the embedding model for a chunk.</summary>
    string ComposeEmbeddingText(JiraDocChunk chunk);
}

/// <summary>LM Studio embedding client.</summary>
public interface IEmbeddingService
{
    /// <summary>Embeds a single text; rejects non-locked dimensions.</summary>
    Task<ReadOnlyMemory<float>> EmbedSingleAsync(string text, CancellationToken cancellationToken = default);

    /// <summary>Embeds a batch of texts.</summary>
    Task<IReadOnlyList<ReadOnlyMemory<float>>> EmbedBatchAsync(IReadOnlyList<string> texts, CancellationToken cancellationToken = default);

    /// <summary>Verifies LM Studio is reachable via /v1/models.</summary>
    Task<bool> VerifyLmStudioAsync(CancellationToken cancellationToken = default);
}

/// <summary>ZVec.NET typed collection facade.</summary>
public interface IVectorStore
{
    /// <summary>Inserts a batch of chunks (sync native path).</summary>
    void InsertBatch(IReadOnlyList<JiraDocChunk> chunks);

    /// <summary>Fetches by Jira key trying typed Id prefixes.</summary>
    JiraDocChunk? FetchByKey(string key, bool includeVector = false);

    /// <summary>Fetches by exact document Id.</summary>
    JiraDocChunk? FetchById(string id, bool includeVector = false);

    /// <summary>Vector similarity query with optional filter.</summary>
    IReadOnlyList<ZVecHitAdapter> Query(
        ReadOnlyMemory<float> queryVector,
        int topK,
        Func<JiraDocChunk, bool>? clientFilter = null,
        bool includeVector = false,
        bool? containsDecision = null,
        int? tier = null,
        string? excludeKey = null);

    /// <summary>Persists chunk ids sidecar for restart rebuild.</summary>
    Task SaveChunkIdsAsync(IEnumerable<string> ids, CancellationToken cancellationToken = default);

    /// <summary>Loads chunk ids sidecar.</summary>
    Task<IReadOnlyList<string>> LoadChunkIdsAsync(CancellationToken cancellationToken = default);

    /// <summary>Wipes on-disk collection and opens a fresh empty one (prevents re-ingest orphans).</summary>
    void RecreateCollection();
}

/// <summary>Adapter so Core does not leak ZVec.NET hit type into all layers.</summary>
public sealed class ZVecHitAdapter
{
    public required JiraDocChunk Record { get; init; }
    public float Score { get; init; }
}

/// <summary>In-memory hierarchy navigation cache.</summary>
public interface IHybridIndex
{
    void Add(JiraDocChunk chunk);
    void AddRange(IEnumerable<JiraDocChunk> chunks);
    JiraDocChunk? GetById(string id);
    JiraDocChunk? GetByKey(string jiraKey);
    IReadOnlyList<JiraDocChunk> GetByEpicLink(string epicLink);
    IReadOnlyList<JiraDocChunk> GetByParentKey(string parentKey);
    IReadOnlyList<JiraDocChunk> GetByTier(int tier);
    void Clear();
    int TotalCount { get; }

    /// <summary>Rebuilds from ZVec using persisted chunk ids + Fetch.</summary>
    Task RebuildFromStoreAsync(CancellationToken cancellationToken = default);
}

/// <summary>Classifies user questions into <see cref="QueryIntent"/>.</summary>
public interface IIntentClassifier
{
    QueryIntent Classify(string userInput);
    string? ExtractIssueKey(string userInput);
}

/// <summary>Navigates project docs for Scenarios A/B/C.</summary>
public interface INavigationEngine
{
    Task<NavigatedContext> NavigateAsync(string userInput, CancellationToken cancellationToken = default);
    Task<NavigatedContext> NavigateFromAssignedIssueAsync(string issueKey, CancellationToken cancellationToken = default);
    Task<NavigatedContext> NavigateFromNewRequirementAsync(string requirementText, CancellationToken cancellationToken = default);
    Task<NavigatedContext> NavigateFromDecisionQuestionAsync(string question, CancellationToken cancellationToken = default);
}

/// <summary>Builds hierarchical RAG context strings.</summary>
public interface IContextBuilder
{
    string Build(NavigatedContext navigation, QueryIntent intent);
}

/// <summary>Streams chat completions from LM Studio.</summary>
public interface IChatService
{
    IAsyncEnumerable<string> StreamAsync(string systemPrompt, string userPrompt, CancellationToken cancellationToken = default);
    Task<string> CompleteAsync(string systemPrompt, string userPrompt, CancellationToken cancellationToken = default);
}

/// <summary>Coordinates Jira fetch → chunk → embed → insert → hybrid index.</summary>
public interface IIngestionOrchestrator
{
    Task<IngestionProgress> RunAsync(CancellationToken cancellationToken = default);
    IngestionProgress GetProgress();
}

/// <summary>Runtime settings updates for LM Studio.</summary>
public interface ISettingsService
{
    LmStudioSettingsDto GetLmStudioSettings();
    void UpdateLmStudioSettings(LmStudioSettingsDto settings);
    Task<bool> VerifyLmStudioAsync(CancellationToken cancellationToken = default);
}
