using PDDM.Core.Abstractions;
using PDDM.Core.Configuration;
using PDDM.Core.Helpers;
using PDDM.Core.Models;
using PDDM.Core.Models.JiraApi;
using PDDM.Shared;
using PDDM.Shared.Constants;

namespace PDDM.Core.Services;

/// <inheritdoc />
public sealed class ChunkingService : IChunkingService
{
    private readonly IDecisionDetector _decisionDetector;
    private readonly PddmRuntimeSettings _runtimeSettings;

    /// <summary>Creates the chunking service.</summary>
    public ChunkingService(IDecisionDetector decisionDetector, PddmRuntimeSettings runtimeSettings)
    {
        _decisionDetector = decisionDetector;
        _runtimeSettings = runtimeSettings;
    }

    /// <inheritdoc />
    public IReadOnlyList<JiraDocChunk> CreateChunks(IReadOnlyList<JiraIssue> issues)
    {
        var ingestion = _runtimeSettings.Current.Ingestion;
        var chunks = new List<JiraDocChunk>();

        foreach (var issue in issues)
        {
            var comments = issue.Fields.Comment?.Comments ?? [];
            var issueType = issue.Fields.Issuetype?.Name ?? "Unknown";
            var isCommentRichType = issueType is JiraIssueTypeNames.Bug
                or JiraIssueTypeNames.Improvement
                or JiraIssueTypeNames.Task;

            if (isCommentRichType && comments.Count < ingestion.MinCommentsForIssue)
                continue;

            var tier = TierMapper.DetermineTier(issueType);
            var epicLink = issue.Fields.EpicLink ?? "";
            var umbrellaLink = ExtractUmbrellaLink(issue);
            var parentKey = DetermineParentKey(issue, tier);
            var components = StringJoinHelper.JoinSemicolon(issue.Fields.Components.Select(c => c.Name));
            var labels = StringJoinHelper.JoinSemicolon(issue.Fields.Labels);
            var fixVersions = StringJoinHelper.JoinSemicolon(issue.Fields.FixVersions.Select(v => v.Name));

            chunks.Add(new JiraDocChunk
            {
                Id = ChunkIdFormatter.FormatIssueId(issueType, issue.Key),
                Tier = tier,
                IssueType = issueType,
                Key = issue.Key,
                EpicLink = tier >= (int)DocTier.Issue ? epicLink : "",
                ParentKey = parentKey,
                UmbrellaLink = umbrellaLink,
                Summary = issue.Fields.Summary,
                Description = issue.Fields.Description ?? "",
                Status = issue.Fields.Status?.Name ?? "Unknown",
                Components = components,
                Labels = labels,
                FixVersions = fixVersions,
                Priority = issue.Fields.Priority?.Name ?? "Unknown",
                Assignee = issue.Fields.Assignee?.DisplayName ?? "Unassigned"
            });

            var commentIndex = 0;
            foreach (var comment in comments)
            {
                if (commentIndex >= ingestion.MaxCommentsPerIssue)
                    break;
                if (_decisionDetector.IsAutoGeneratedComment(comment.Body))
                    continue;

                chunks.Add(new JiraDocChunk
                {
                    Id = ChunkIdFormatter.FormatCommentId(issue.Key, commentIndex),
                    Tier = (int)DocTier.Comment,
                    IssueType = JiraIssueTypeNames.Comment,
                    Key = issue.Key,
                    EpicLink = epicLink,
                    ParentKey = issue.Key,
                    UmbrellaLink = umbrellaLink,
                    Description = comment.Body,
                    Components = components,
                    Labels = labels,
                    FixVersions = fixVersions,
                    CommentAuthor = comment.Author?.DisplayName ?? "Unknown",
                    ContainsDecision = _decisionDetector.IsDecisionComment(comment.Body)
                });
                commentIndex++;
            }
        }

        return chunks;
    }

    /// <inheritdoc />
    public string ComposeEmbeddingText(JiraDocChunk chunk) => chunk.Tier switch
    {
        (int)DocTier.EpicOrUmbrella => $"{chunk.Summary}: {chunk.Description}",
        (int)DocTier.Issue => $"{chunk.Key}: {chunk.Summary}\n{chunk.Description}\nType: {chunk.IssueType}",
        (int)DocTier.SubTask => $"{chunk.Key}: {chunk.Summary}\n{chunk.Description}",
        (int)DocTier.Comment => $"On {chunk.ParentKey}: {chunk.CommentAuthor} said: {chunk.Description}",
        _ => $"{chunk.Key}: {chunk.Summary}\n{chunk.Description}"
    };

    private static string DetermineParentKey(JiraIssue issue, int tier)
    {
        if (tier == (int)DocTier.SubTask)
            return issue.Fields.Parent?.Key ?? "";
        return "";
    }

    private static string ExtractUmbrellaLink(JiraIssue issue)
    {
        foreach (var link in issue.Fields.Issuelinks ?? [])
        {
            if (link.OutwardIssue?.Issuetype?.Name == JiraIssueTypeNames.Umbrella)
                return link.OutwardIssue.Key;
            if (link.InwardIssue?.Issuetype?.Name == JiraIssueTypeNames.Umbrella)
                return link.InwardIssue.Key;
        }

        return "";
    }
}
