using PDDM.Core.Abstractions;
using PDDM.Core.Constants;

namespace PDDM.Core.Services;

/// <inheritdoc />
public sealed class DecisionDetector : IDecisionDetector
{
    /// <inheritdoc />
    public bool IsDecisionComment(string commentBody)
    {
        if (string.IsNullOrWhiteSpace(commentBody))
            return false;

        var lower = commentBody.ToLowerInvariant();
        return DecisionKeywords.All.Any(kw => lower.Contains(kw, StringComparison.Ordinal));
    }

    /// <inheritdoc />
    public bool IsAutoGeneratedComment(string commentBody)
    {
        if (string.IsNullOrWhiteSpace(commentBody))
            return true;

        return AutoGeneratedCommentPatterns.All.Any(p =>
            commentBody.Contains(p, StringComparison.OrdinalIgnoreCase));
    }
}
