<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDDM.Core\PDDM.Core.csproj" />
    <ProjectReference Include="..\PDDM.Shared\PDDM.Shared.csproj" />
    <ProjectReference Include="..\PDDM.ServiceDefaults\PDDM.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
